### ISSUE TITLE
Server is listening only for local connections

### ISSUE THREAD

**Issue by abraverm** [RedHat-Israel/rosvr-client#3]
You can't access the server with smartphone (same network) when running `yarn run start-server`.

**Comment by shakedlokits** [comment]
This issue is triggered by #4

**Comment by abraverm** [comment]
how exactly the two issue are related?

**Comment by shakedlokits** [comment]
Because a development server should listen only to local connections, but due to Chrome permissions, this is an unwanted behavior on our case. Hence, one triggers the other.

**Comment by abraverm** [comment]
I agree that in most cases development server should listen only to local connections. But in WebVR I think most developers would like to check the results in their clients (smartphones). So the question is why is it critical to stick with local connections ?
